#!/usr/bin/env bash
# Script transfer file from our client to a server
# Must have IP, file path, username and ssh private key path
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o stricthostkeychecking=no "$1" "$3@$2":~/
fi