#!/usr/bin/env bash
# Script installs nginx
# Returns a page that contains "Holberton School"
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start