#!/usr/bin/env bash
# Script that launches nginx as user - nginx
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
# sudo chown -R nginx /var/log/nginx/ /etc/nginx/ /usr/share/nginx/
# sudo chmod 755 /etc/nginx/nginx.conf
pkill apache2
# su nginx -c nginx
