#!/usr/bin/env bash
# Script installs nginx and creates a custom greeting when called
# Provides a redirect_me link
# And replies Ceci n'est pas une page as a 404
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "26i rewrite ^/redirect_me https://www.holbertonschool.com permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "26i error_page 404 /custom_404.html;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "17i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
