#!/usr/bin/env bash
# Script to print "To infinity and beyond" indefinitely
# Also displays "I am invincible!!!" when receiving SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done