#!/usr/bin/env bash
# This script displays "Holberton School" at all numbers except 9 with while
i=1
while [ $i -le 10 ]
do
    echo Holberton School
    if [ $i -eq 9 ]
    then
     	echo Hi
    fi
    let i+=1
done
