#!/usr/bin/env bash
# This script displays the content of current directory in list format
# only part of name after first dash is displayed
LIST="$(ls)"
for i in $LIST
do
    echo "$i" | rev | cut -d'-' -f 1 | rev
done
