#!/usr/bin/env bash
# This script displays 1 to 100 with
# multiples of 3 = Fizz
# multiples of 5 = Buzz
# multies of 3 and 5 = FizzBuzz
for i in {1..100}
do
    if [ $((i%15)) == 0 ]
    then
	echo FizzBuzz
    elif [ $((i%5)) == 0 ]
    then
	echo Buzz
    elif [ $((i%3)) == 0 ]
    then
	echo Fizz
    else
	echo $i
    fi
done
