#!/usr/bin/env bash
# This script displays "Holberton School" at all numbers except 9 with while
i=0
while [ $i -lt 10 ]
do
    if [ $i == 8 ]
    then
     	echo Hi
    else
	echo Holberton School
    fi
    let i+=1
done
