#!/usr/bin/env bash
# This script displays "bad luck" for 4 "good luck" for 8 and "Holberton School"
# for the rest using while/if/elif/else
i=0
while [ $i -lt 10 ]
do
      if [ $i == 3 ]
      then
      	 echo bad luck
      elif [ $i == 7 ]
      then
      	 echo good luck
      else
	 echo Holberton School
      fi
      let i+=1
done
