#!/usr/bin/env bash
# This script shows 12 hours with their possible min combination using while
hour=0
while [ $hour -lt 13 ]
do
    echo Hour: $hour
    min=0
    while [ $min -lt 60 ]
    do
      	echo $min
	let min+=1
    done
    let hour+=1
done
